server:
  port: 7300

spring:
  application:
    name: zuul-service

eureka:
  client:
    instance:
      hostname: localhost
    serviceUrl:
      defaultZone: http://localhost:4010/eureka

zuul:
  prefix: /api
  routes:
    member-service:
      path: /service/**
      url: http://localhost:8081